
{'date': 'Fri Dec 04 2020 16:21:44.757 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 64
  def __init__()
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 04 2020 16:54:47.667 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 89
    desafio_2().inicia()
  module <module> line 39
    self.texto_1 = Texto(cena1, txt = "Encontre o livro")
NameError: name 'cena1' is not defined
'''},
{'date': 'Fri Dec 04 2020 16:55:18.114 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 89
    desafio_2().inicia()
  module <module> line 39
    self.texto_1 = Texto(cena1, txt = "Encontre o livro")
NameError: name 'cena1' is not defined
'''},
{'date': 'Fri Dec 04 2020 16:56:05.562 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 89
    desafio_2().inicia()
TypeError: inicia() takes 0 positional argument but more were given
'''},
{'date': 'Fri Dec 04 2020 17:19:32.808 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  print(self.resposta2, isinstance(str,self.resposta2)
                                                                                                                                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 04 2020 17:19:48.217 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  print(self.resposta2, isinstance(self.resposta2,str)
                                                                                                                                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 04 2020 17:20:10.413 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  print(self.resposta2, isinstance(str,self.resposta2)
                                                                                                                                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 04 2020 17:21:16.921 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  print(self.resposta2, self.resposta2.isalpha(
                                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 04 2020 17:21:30.213 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  print(self.resposta2, self.resposta2.isalpha()
                                                                                                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 04 2020 17:23:27.169 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 67
  if self.resposta2 == 'va para a biblioteca' or 'vá para a biblioteca' :
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sat Dec 05 2020 15:12:10.320 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 44
  cena = self.cena1)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Dec 11 2020 18:37:58.142 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 84
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 18:38:33.540 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 84
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 18:39:07.429 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 84
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 19:26:58.758 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  from elizabeth.meredith import Entrada, global nome_personagem
                                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 11 2020 19:30:40.132 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  from elizabeth.meredith import Entrada, global nome_personagem
                                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 11 2020 19:30:50.307 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 84
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 19:34:21.110 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 84
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 19:34:31.261 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  from meredith.main import Entrada, global nome_personagem
                                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 11 2020 20:21:56.833 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
  module meredith.main line 11
    from libby.main import desafio_2
  module libby.main line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
  module meredith.main line 11
    from libby.main import desafio_2
  module libby.main line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Fri Dec 11 2020 20:22:07.770 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'
'''},
{'date': 'Fri Dec 11 2020 20:32:47.319 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
  module meredith.main line 11
    from libby.main import desafio_2
  module libby.main line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
  module meredith.main line 11
    from libby.main import desafio_2
  module libby.main line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Fri Dec 11 2020 20:33:06.684 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 32
    class desafio_2:
  module <module> line 33
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'
'''},
{'date': 'Fri Dec 11 2020 20:42:14.304 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 82
    desafio_2().inicia()
  module <module> line 39
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 20:42:30.778 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 83
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 20:42:52.17 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 83
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 20:46:12.879 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 83
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 11 2020 20:46:44.748 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 83
    desafio_2().inicia()
  module <module> line 40
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Tue Dec 15 2020 13:39:50.480 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Tue Dec 15 2020 13:39:58.356 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Tue Dec 15 2020 13:40:01.435 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Tue Dec 15 2020 13:40:08.219 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Tue Dec 15 2020 15:06:55.175 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Tue Dec 15 2020 15:11:25.879 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Tue Dec 15 2020 15:43:22.391 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Tue Dec 15 2020 15:43:24.175 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.cena1, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 16 2020 17:39:20.875 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 16 2020 17:39:22.65 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 16 2020 17:39:23.157 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 16 2020 17:39:24.200 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 16 2020 17:39:25.474 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 14:07:39.630 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 23:10:51.473 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 23:11:27.885 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 23:11:36.943 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 23:55:11.905 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 23:57:40.776 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 23 2020 18:05:40.57 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Wed Dec 23 2020 18:06:20.111 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from meredith.main import nome_personagem
'''},
{'date': 'Wed Dec 23 2020 18:11:10.399 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 83
    self.cena1.vai()
AttributeError: 'desafio_2' object has no attribute 'cena1'
'''},
{'date': 'Wed Dec 23 2020 18:56:21.995 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 83
    self.cena1.vai()
AttributeError: 'desafio_2' object has no attribute 'cena1'
'''},
{'date': 'Tue Jan 05 2021 12:23:16.629 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Tue Jan 05 2021 12:23:18.514 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 44
    self.texto_1 = Texto(self.QUARTO, txt = f'{nome_personagem},Encontre o livro')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Tue Jan 05 2021 12:24:10.641 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 83
    self.cena1.vai()
AttributeError: 'desafio_2' object has no attribute 'cena1'
'''},
{'date': 'Tue Jan 05 2021 12:24:47.182 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    desafio_2().inicia()
  module <module> line 83
    self.cena1.vai()
AttributeError: 'desafio_2' object has no attribute 'cena1'
'''},
{'date': 'Tue Jan 05 2021 13:07:21.572 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  w=55,h=58,  x=815,73, y=426,37, # ou x=eixo_x, y=eixo_y, w=largura, h=altura
                      ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Tue Jan 05 2021 13:07:23.485 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  w=55,h=58,  x=815,73, y=426,37, # ou x=eixo_x, y=eixo_y, w=largura, h=altura
                      ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Tue Jan 05 2021 13:08:07.264 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 53
  w=55,h=58,  x=815,73, y=426,37, # ou x=eixo_x, y=eixo_y, w=largura, h=altura
                      ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Tue Jan 05 2021 13:17:20.312 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 97
    desafio_2().inicia()
  module <module> line 52
    self.LIVRO= Elemento(imagem_livro, tit="Livro",
AttributeError: 'desafio_2' object has no attribute 'QUARTO2'
'''},
{'date': 'Tue Jan 05 2021 13:20:43.773 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 36
    class desafio_2:
  module <module> line 73
    self.LIVRO= Elemento(imagem_livro, tit="Livro",
AttributeError: 'GUI' object has no attribute 'QUARTO2'
'''},
{'date': 'Tue Jan 05 2021 14:18:33.684 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 100
    desafio_2().inicia()
  module <module> line 45
    self.LIVRO= Elemento(imagem_livro, tit="Livro",
AttributeError: 'desafio_2' object has no attribute 'QUARTO2'
'''},
{'date': 'Thu Jan 07 2021 18:20:23.384 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 64
  self.texto_2= Texto(self.cena2, 
                                                                                                                                                                                                                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Jan 07 2021 18:24:39.824 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 35
    class desafio_2:
  module <module> line 64
    self.texto_2= Texto(self.cena2, 
AttributeError: 'GUI' object has no attribute 'cena2'
'''},
{'date': 'Thu Jan 07 2021 19:20:20.807 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 47
  self.LIVRO= Elemento(imagem_livro, tit="Livro",
                                                                                                                                                                                                                                                                                                                                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Jan 07 2021 19:20:32.911 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    desafio_2().inicia()
  module <module> line 62
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
NameError: name 'funcao_de_acao_do_botao2' is not defined
'''},
{'date': 'Thu Jan 07 2021 19:27:38.939 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 103
    desafio_2().inicia()
  module <module> line 61
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
NameError: name 'funcao_de_acao_do_botao2' is not defined
'''},
{'date': 'Thu Jan 07 2021 19:29:14.510 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    desafio_2().inicia()
  module <module> line 81
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
NameError: name 'funcao_de_acao_do_botao2' is not defined
'''},
{'date': 'Thu Jan 07 2021 19:32:56.92 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 37
    class desafio_2:
  module <module> line 83
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
AttributeError: 'GUI' object has no attribute 'cena2'
'''},
{'date': 'Thu Jan 07 2021 19:34:20.954 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 37
    class desafio_2:
  module <module> line 85
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
AttributeError: 'GUI' object has no attribute 'cena2'
'''},
{'date': 'Thu Jan 07 2021 19:35:47.515 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 85
  self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
  ^
IndentationError: unexpected indent
'''},
{'date': 'Thu Jan 07 2021 19:40:28.625 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 37
    class desafio_2:
  module <module> line 85
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
AttributeError: 'GUI' object has no attribute 'cena2'
'''},
{'date': 'Fri Jan 08 2021 11:48:19.213 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 37
    class desafio_2:
  module <module> line 85
    self.BOTAO_DESAFIO1= Elemento(botao_desafio1, tit="PLAY",
AttributeError: 'GUI' object has no attribute 'cena2'
'''},